import Header from './header/header'
import Hcomp from './header/hcomp'
import Home from './home/home'
import About from './about/about'
import Hobby from './hobby/hobby'
import Portfolio from './portfolio/portfolio'
import PlateHobby from './hobby/plateHobby'
import PlatePortfolio from './portfolio/platePortfolio'
import Footer from './footer/footer'

export {default as Header} from './header/header'
export {default as Hcomp} from './header/hcomp'
export {default as Home} from './home/home'
export {default as About} from './about/about'
export {default as Hobby} from './hobby/hobby'
export {default as Portfolio} from './portfolio/portfolio'
export {default as PlateHobby} from './hobby/plateHobby'
export {default as PlatePortfolio} from './portfolio/platePortfolio'
export {default as Footer} from './footer/footer'